### ISSUE TITLE
中文数据集上few-shot评价效果怎么样呢

### ISSUE THREAD

**Issue by qiutzh** [artpli/CodeIE#1]
很棒的工作，请问作者有在中文数据集上验证ChatGPT的Few-Shot抽取效果吗，特别是关系抽取任务。

**Comment by artpli** [comment]
您好，感谢关注！
抱歉我本人没有在中文数据集上测试ChatGPT的Few-shot code prompt抽取效果；不过使用ChatGPT做中文IE的paper有[Zero-Shot Information Extraction via Chatting with ChatGPT](https://arxiv.org/pdf/2302.10205.pdf)。
根据一些读者的反馈和补充的实验结果，CodeIE的实验结论大概率在ChatGPT系列大模型上有效，在llama等模型上的效果有待进一步考证。
希望能解答您的问题！

**Comment by artpli** [comment]
@qiutzh 您好，我最近在中文医疗信息抽取任务上做了简单的ChatGPT测试，初步结果是在NER任务上代码风格的提示词优势不明显，但是在关系抽取上效果明显。这一定程度上是因为UIE为了统一不同类型的任务，设计的关系抽取schema并不易于语言模型理解和生成，CodeIE中提供的关系抽取的“实体”“关系”抽取顺序、文本从前向后抽取顺序、代码风格的marker都有助于大语言模型生成正确结果。
