### ISSUE TITLE
论文问题咨询

### ISSUE THREAD

**Issue by jy-101361-1810897** [artpli/CodeIE#2]
用code prompt会提升gpt-3.5（非codeLLM，没有专门用code训练过）表现得原因是什么呢？谢谢

**Comment by artpli** [comment]
嗨您好，感谢对我们论文的关注！

我觉得一个主要的原因是如果prompt(尤其是其结构)非常偏向natural language, 那么由于NL-LLM在海量自然文本上训练过，会导致其输出很不可控，很容易输出不符合结构的结果（比如左括号和右括号的数量不一致），从而导致解析失败。而NL-LLM往往在少量code上训练过，并且其结构往往更加统一，比如很多dict的结构，那么在NL-LLM上使用code-prompt就更能解析出更多的正确输出。另外还有一些其他的可能的分析，我们当时也已经尽量把相关的量化结果都放在了论文中的分析环节。但是由于时间资源以及对黑盒LLM背后的训练语料未知等因素，我们也还没有一个非常确切的证据，也欢迎一块探讨！

再次感谢关注！
祝好!
Peng Li
